### ISSUE TITLE
Hora no visor

### ISSUE THREAD

**Issue by menigma2** [leandrotsampa/e2d-hi3798cv200#1]
Após iniciar o sistema mostra hora correta n tela.
Mas no visor ele sempre mostra o horário de 08:12 não sai deste horário
![IMG_20200412_184957](https://user-images.githubusercontent.com/22132116/79080876-ff916200-7cee-11ea-9c63-1eca04f016a3.jpg)

**Comment by leandrotsampa** [comment]
Nessa versão está faltando o plugin do visor,
Você pode baixar e compilar: [VFDControl](https://gitlab.com/leandrotsampa/VFDControl)
Ou esperar que eu adicione a última release aqui.

**Comment by menigma2** [comment]
Baixei a ultima versão do dia 10/04/2020 que esta resolvido este problema.
Muito obrigado, por todo seu trabalho.

**Comment by diotto** [comment]
Boa noite @menigma2 e @leandrotsampa , onde baixo a versão de 10/04? Não achei aqui no GitHub. Obrigado!

**Comment by leandrotsampa** [comment]
> Boa noite @menigma2 e @leandrotsampa , onde baixo a versão de 10/04? Não achei aqui no GitHub. Obrigado!

https://leandro.azsat.org/

Não esqueça do upk, porém tem outra versão que ainda não liberei.

**Comment by diotto** [comment]
Obrigado @leandrotsampa !!!
